### ISSUE TITLE
Detection of XSpec test type remembers another file by same name in different directory

### ISSUE THREAD

**Issue by galtm** [nkutsche/xspec-maven-plugin#7] opened 2023-10-17 11:32 UTC
If I have two test files by the same name in different directories, where one is a test for XSLT and one is a test for Schematron, then the `mvn test` operation fails because it expects both tests to be the same type.

Below is an excerpt of a [log](https://github.com/galtm/xslt-accumulator-tools/actions/runs/6546415756/job/17776825362?pr=20) that reproduces the error. You can see that the process includes these files

- `src/sample-acc/test/acc-reporter.xspec`: Test for Schematron; see https://github.com/galtm/xslt-accumulator-tools/pull/20/files
- `src/test/acc-reporter.xspec`: Test for XSLT; see https://github.com/galtm/xslt-accumulator-tools/blob/main/src/test/acc-reporter.xspec

```
[INFO] Found XSpec file /home/runner/work/xslt-accumulator-tools/xslt-accumulator-tools/src/sample-acc/test/acc-reporter.xspec
[INFO] 
[INFO] Processing /home/runner/work/xslt-accumulator-tools/xslt-accumulator-tools/src/sample-acc/test/acc-reporter.xspec to /home/runner/work/xslt-accumulator-tools/xslt-accumulator-tools/target/xspecmaven/temp/acc-reporter.xspec-xml-to-prop.xml
[INFO] Loading stylesheet /home/runner/work/xslt-accumulator-tools/xslt-accumulator-tools/target/xspecmaven/test-type.xsl
[INFO] Start XSpec process for /home/runner/work/xslt-accumulator-tools/xslt-accumulator-tools/src/sample-acc/test/acc-reporter.xspec
Warning:  Trying to override old definition of task xml-to-properties
Warning:  Testing acc-reporter.xspec [s]
.
.
.
[INFO] Found XSpec file /home/runner/work/xslt-accumulator-tools/xslt-accumulator-tools/src/test/acc-reporter.xspec
[INFO] 
[INFO] Start XSpec process for /home/runner/work/xslt-accumulator-tools/xslt-accumulator-tools/src/test/acc-reporter.xspec
Warning:  Trying to override old definition of task xml-to-properties
Warning:  Testing acc-reporter.xspec [s]
[INFO] Processing /home/runner/work/xslt-accumulator-tools/xslt-accumulator-tools/src/test/acc-reporter.xspec to /home/runner/work/xslt-accumulator-tools/xslt-accumulator-tools/target/xspecmaven/xspec-temp-files/acc-reporter-sch-preprocessed.xsl
[INFO] Loading stylesheet /home/runner/work/xslt-accumulator-tools/xslt-accumulator-tools/target/xspecmaven/xspec-framework/xspec-2.3.2/src/schematron/schut-to-xslt.xsl
[INFO] Processing /home/runner/work/xslt-accumulator-tools/xslt-accumulator-tools/src/test/acc-reporter.xspec to /home/runner/work/xslt-accumulator-tools/xslt-accumulator-tools/target/xspecmaven/xspec-temp-files/acc-reporter-sch-preprocessed.xspec
[INFO] Loading stylesheet /home/runner/work/xslt-accumulator-tools/xslt-accumulator-tools/target/xspecmaven/xspec-framework/xspec-2.3.2/src/schematron/schut-to-xspec.xsl
ERROR in x:description: Missing @schematron.
[INFO] /home/runner/work/xslt-accumulator-tools/xslt-accumulator-tools/target/xspecmaven/xspec-framework/xspec-2.3.2/src/schematron/schut-to-xslt.xsl:168:53: Fatal Error! Processing terminated by xsl:message at line 168 in schut-to-xslt.xsl
[INFO] Failed to process /home/runner/work/xslt-accumulator-tools/xslt-accumulator-tools/src/test/acc-reporter.xspec
/home/runner/work/xslt-accumulator-tools/xslt-accumulator-tools/target/xspecmaven/build.xml:83: The following error occurred while executing this line:
/home/runner/work/xslt-accumulator-tools/xslt-accumulator-tools/target/xspecmaven/build.xml:104: The following error occurred while executing this line:
/home/runner/work/xslt-accumulator-tools/xslt-accumulator-tools/target/xspecmaven/xspec-wrapper.xml:27: The following error occurred while executing this line:
/home/runner/work/xslt-accumulator-tools/xslt-accumulator-tools/target/xspecmaven/xspec-framework/xspec-2.3.2/build.xml:335: The following error occurred while executing this line:
/home/runner/work/xslt-accumulator-tools/xslt-accumulator-tools/target/xspecmaven/xspec-framework/xspec-2.3.2/build.xml:196: Fatal error during transformation using /home/runner/work/xslt-accumulator-tools/xslt-accumulator-tools/target/xspecmaven/xspec-framework/xspec-2.3.2/src/schematron/schut-to-xslt.xsl: Processing terminated by xsl:message at line 168 in schut-to-xslt.xsl; SystemID: file:/home/runner/work/xslt-accumulator-tools/xslt-accumulator-tools/target/xspecmaven/xspec-framework/xspec-2.3.2/src/schematron/schut-to-xslt.xsl; Line#: 168; Column#: 53
	at org.apache.tools.ant.ProjectHelper.addLocationToBuildException(ProjectHelper.java:582)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:440)
	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:106)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at java.base/java.util.Vector.forEach(Vector.java:1394)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:67)
	at net.sf.antcontrib.logic.ForEach.executeSequential(ForEach.java:178)
	at net.sf.antcontrib.logic.ForEach.execute(ForEach.java:254)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at jdk.internal.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
[INFO] ------------------------------------------------------------------------
	at org.apache.tools.ant.Target.execute(Target.java:449)
[INFO] BUILD FAILURE
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
[INFO] ------------------------------------------------------------------------
```

In the real situation where I first encountered this phenomenon, it was the opposite: the detection thought both tests were for XSLT and the error was about a missing `@stylesheet` attribute. (In my real situation, I can work around this by making the test filenames unique.)

Thanks for making this useful plug-in.

**Comment by nkutsche** [comment] 2023-11-11 16:30
Sorry @galtm, my settings was misconfigured, so that I didn't get any notifications for this repo.

I think the problem is the old Ant story of unmutable properties.

As a workaround you should use two different plugin executions by Maven with different `<testDir>` and/or `<includes>|<excludes>`.

I would recommend something like this:

```xml
<executions>
    <execution>
        <id>run-xspec</id>
        <goals>
            <goal>run-xspec</goal>
        </goals>
        <phase>test</phase>
        <configuration>
            <testDir>src/test</testDir>
            <excludes>
                <exclude>maven-helper.xspec</exclude>
            </excludes>
        </configuration>
    </execution>
    <execution>
        <id>run-xspec-sch</id>
        <goals>
            <goal>run-xspec</goal>
        </goals>
        <phase>test</phase>
        <configuration>
            <testDir>src/sample-acc/test</testDir>
        </configuration>
    </execution>
</executions>
<configuration>
    <addDependenciesToClasspath>true</addDependenciesToClasspath>
    <generateSurefireReport>true</generateSurefireReport>
</configuration>
```

**Comment by galtm** [comment] 2023-11-12 17:51
The phrase "old Ant story" seems to imply that either this isn't fixable or it's not worth the trouble to fix it. That's fine with me, now that I know about the issue and have two viable workarounds to choose from. Thanks for suggesting the second workaround, @nkutsche .

**Comment by nkutsche** [comment] 2023-11-13 08:41
> The phrase "old Ant story" seems to imply that either this isn't fixable or it's not worth the trouble to fix it.

No, it's just a common problem when you do something in Ant for what Ant wasn't designed. And it was just a guess, actually it is a similar problem but slightly different.

I will see if I can make a patch for this.

However, in my opinion it is recommended to make a clear distinction between testing Schematron and testing XSLT. Having different executions for each might not be a bad idea.

**Comment by galtm** [comment] 2023-11-13 11:29
Thanks for clarifying and for looking into the possibility of a patch.

I agree with your recommendation about difference executions, in general. It could be that the actual situation in which I ran into this issue is an edge case. (I write about XSpec at https://medium.com/@xspectacles and make the code examples available at https://github.com/galtm/xspectacles . Sometimes, I provide examples in multiple languages to support the same topic, and I organize the GitHub repo by topic. For production code, I would probably organize the files by language and follow suit in pom.xml.)

**Comment by nkutsche** [comment] 2023-11-13 12:50
I just published [Version 2.0.1](https://github.com/nkutsche/xspec-maven-plugin/releases/tag/releases%2Fv2.0.1) which should fix this issue.

It will take some time until it is available on Maven central (at least until tomorrow I think).

**Comment by galtm** [comment] 2023-11-13 16:08
Thanks, @nkutsche !

**Comment by galtm** [comment] 2023-11-14 21:20
I repeated my steps to reproduce the issue and confirmed that v2.0.1 fixes it. Thanks again.

**Comment by nkutsche** [comment] 2023-11-15 06:17
Great! Thanks for the feedback.

So I can close the issue.

**Closed as completed by nkutsche** 2023-11-15 06:17 UTC
